[package]
name = "rascii"
description = "Process image into colored-ascii image"
version = "0.1.1"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
image = {version = "0.25.2", features = ["rayon"] }
