[package]
name = "rustascii-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
rustascii = { git = "https://github.com/itsthomashere/rustascii"}
