[package]
name = "ascii-rs"
description = "Process image into colored-ascii image"
version = "0.1.2"
edition = "2021"
license = "MIT"

[dependencies]
ansi_term = "0.12.1"
image = {version = "0.25.2", features = ["rayon"] }
