[package]
name = "rascii-cli"
description = "CLI tool for ascii-rs image rendering"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
ascii-rs = "0.1.1"
clap = { version = "4.5.20", features = ["derive"] }
